# BladeFall worldserver settings
# Apply these values to env/dist/etc/worldserver.conf.

CharacterCreating.MinLevelForHeroicCharacter = 0
StartPlayerLevel = 68
StartHeroicPlayerLevel = 68
StartPlayerMoney = 1000000
StartHeroicPlayerMoney = 1000000
AlwaysMaxSkillForLevel = 1
Rate.XP.Kill = 3
Rate.XP.Quest = 3
Rate.XP.Quest.DF = 3
Rate.XP.Explore = 3
Rate.XP.Pet = 3
Rate.Reputation.Gain = 3
Rate.Skill.Discovery = 3
SkillGain.Crafting = 3
SkillGain.Gathering = 3
SkillGain.Defense = 1
SkillGain.Weapon = 1
